import type { SectionKey } from "@/components/quote/types";

/** Maps imported Home quote fields to the workspace section that reveals them. */
export const HOME_SECTION_FIELDS: Record<SectionKey, readonly string[]> = {
  loan: [
    "productId",
    "loanPurpose",
    "rateType",
    "fixedPeriodMonths",
    "loanAmount",
    "propertyValue",
    "loanTermYears",
  ],
  risk: [
    "creditScore",
    "creditScores",
    "dtiRatio",
    "grossAnnualIncome",
    "serviceabilityIncomeMeasure",
    "serviceabilityNsi",
    "currentCustomerRate",
    "retentionArrearsHardship18Months",
    "retentionArrearsPast12Months",
    "riskNotes",
  ],
  relationship: [
    "yearsAsMember",
    "existingLenderLoan",
    "lenderProducts",
    "relationshipNotes",
  ],
  competitor: [
    "livesInServiceRegion",
    "vipCustomer",
    "competitorLender",
    "competitorRate",
    "competitorNotes",
    "requestedRate",
    "requestedReason",
    "requestedReasonNotes",
  ],
  profitability: [
    "brokerName",
    "brokerCompany",
    "brokerInRegion",
    "brokerVolumeBand",
    "brokerDiscretionPct",
    "costOfFunds",
    "commissions",
    "otherIncome",
    "upfrontFeeOverride",
    "monthlyFeeOverride",
    "expenses",
  ],
  capital: [
    "capitalStandardStatus",
    "eligibleLmi",
    "homeGuaranteeSchemeEligible",
    "riskWeightOverridePct",
    "taxRateOverridePct",
    "capitalOverrideReason",
  ],
  notes: ["notes"],
};

/** DOM targets used to focus the first invalid/imported Home quote field. */
export const HOME_INPUT_IDS: Readonly<Record<string, string>> = {
  productId: "product",
  fixedPeriodMonths: "fixed-period",
  loanAmount: "loan-amount",
  propertyValue: "property-value",
  loanTermYears: "loan-term",
  creditScore: "credit-score-0",
  creditScores: "credit-score-0",
  dtiRatio: "dti-ratio",
  grossAnnualIncome: "gross-income",
  serviceabilityNsi: "serviceability-nsi",
  currentCustomerRate: "current-customer-rate",
  yearsAsMember: "years-as-member",
  competitorRate: "competitor-rate",
  requestedRate: "requested-rate",
  requestedReasonNotes: "requested-reason-notes",
  costOfFunds: "cost-of-funds",
  upfrontFeeOverride: "home-upfront-fee-override",
  monthlyFeeOverride: "home-monthly-fee-override",
  capitalStandardStatus: "capital-standard-status",
  riskWeightOverridePct: "capital-risk-override",
  taxRateOverridePct: "capital-tax-rate-override",
  capitalOverrideReason: "capital-override-reason",
  notes: "quote-notes",
};
