export const COMMERCIAL_SECTION_FIELDS = {
  facility: [
    "businessName",
    "abn",
    "facilityType",
    "loanAmount",
    "propertyTransactionType",
    "purchasePrice",
    "customerEquityContribution",
    "loanTermYears",
    "securities",
  ],
  risk: [
    "industryCategory",
    "businessRiskGrade",
    "yearsTrading",
    "annualRevenue",
    "ebitda",
    "existingAnnualDebtService",
    "financialsQuality",
    "financialsAgeMonths",
    "revenueTrend",
    "profitTrend",
    "taxStatus",
  ],
  relationship: [
    "existingRelationship",
    "operatingInRegion",
    "yearsWithLender",
    "otherLenderExposure",
  ],
  profitability: [
    "expectedUtilisationPct",
    "costOfFunds",
    "commissions",
    "otherIncome",
    "upfrontFeeOverride",
    "monthlyFeeOverride",
    "expenses",
  ],
  capital: [
    "apsExposureClass",
    "capitalClassificationConfirmed",
    "riskWeightOverridePct",
    "taxRateOverridePct",
    "creditConversionFactorOverridePct",
    "capitalOverrideReason",
  ],
  requested: [
    "competitorLender",
    "competitorRate",
    "competitorNotes",
    "requestedRate",
    "requestedReason",
    "requestedReasonNotes",
    "notes",
  ],
} as const;

export const COMMERCIAL_LOAN_TYPE_OPTIONS = [
  { value: "standard", label: "Standard" },
  { value: "non_standard", label: "Non-Standard" },
] as const;

export const COMMERCIAL_INPUT_IDS: Readonly<Record<string, string>> = {
  businessName: "cl-business",
  abn: "cl-abn",
  facilityType: "cl-facility",
  loanAmount: "cl-amount",
  propertyTransactionType: "cl-property-transaction-type",
  purchasePrice: "cl-purchase-price",
  customerEquityContribution: "cl-equity-contribution",
  loanTermYears: "cl-term",
  industryCategory: "cl-industry",
  businessRiskGrade: "cl-grade",
  yearsTrading: "cl-trading",
  annualRevenue: "cl-revenue",
  ebitda: "cl-ebitda",
  existingAnnualDebtService: "cl-debtservice",
  financialsQuality: "cl-financials-quality",
  financialsAgeMonths: "cl-financials-age",
  revenueTrend: "cl-revenue-trend",
  profitTrend: "cl-profit-trend",
  taxStatus: "cl-tax-status",
  operatingInRegion: "cl-operating-in-region",
  yearsWithLender: "cl-yearswith",
  otherLenderExposure: "cl-exposure",
  expectedUtilisationPct: "cl-utilisation",
  costOfFunds: "cl-cost-funds",
  upfrontFeeOverride: "commercial-upfront-fee-override",
  monthlyFeeOverride: "commercial-monthly-fee-override",
  apsExposureClass: "capital-exposure-class",
  riskWeightOverridePct: "capital-risk-override",
  taxRateOverridePct: "capital-tax-rate-override",
  creditConversionFactorOverridePct: "capital-ccf-override",
  capitalOverrideReason: "capital-override-reason",
  competitorLender: "competitor-lender",
  competitorRate: "competitor-rate",
  competitorNotes: "competitor-notes",
  requestedRate: "requested-rate",
  requestedReason: "requested-rate-reason",
  requestedReasonNotes: "requested-reason-notes",
  notes: "cl-notes",
};
