export const PERSONAL_SECTION_FIELDS = {
  loan: [
    "productId",
    "loanPurpose",
    "securityType",
    "loanAmount",
    "loanTermMonths",
  ],
  risk: [
    "creditScore",
    "creditScores",
    "employmentIncomeStability",
    "currentCustomerRate",
    "retentionArrearsHardship18Months",
    "retentionArrearsPast12Months",
    "riskNotes",
  ],
  relationship: ["existingMember", "yearsAsMember"],
  affordability: [
    "netMonthlyIncome",
    "monthlyLivingExpenses",
    "existingMonthlyDebtRepayments",
  ],
  requested: [
    "competitorLender",
    "competitorRate",
    "competitorNotes",
    "requestedRate",
    "requestedReason",
    "requestedReasonNotes",
  ],
  profitability: [
    "costOfFunds",
    "commissions",
    "otherIncome",
    "upfrontFeeOverride",
    "monthlyFeeOverride",
    "expenses",
  ],
  capital: [
    "riskWeightOverridePct",
    "taxRateOverridePct",
    "capitalOverrideReason",
  ],
  notes: ["notes"],
} as const;

export const PERSONAL_INPUT_IDS: Readonly<Record<string, string>> = {
  productId: "pl-product",
  loanPurpose: "pl-purpose",
  loanAmount: "pl-amount",
  loanTermMonths: "pl-term",
  creditScore: "pl-score-0",
  creditScores: "pl-score-0",
  employmentIncomeStability: "pl-employment",
  yearsAsMember: "pl-years-member",
  netMonthlyIncome: "pl-income",
  monthlyLivingExpenses: "pl-expenses",
  existingMonthlyDebtRepayments: "pl-debt",
  competitorLender: "competitor-lender",
  competitorRate: "competitor-rate",
  competitorNotes: "competitor-notes",
  requestedRate: "requested-rate",
  requestedReason: "requested-rate-reason",
  requestedReasonNotes: "requested-reason-notes",
  costOfFunds: "pl-cost-funds",
  upfrontFeeOverride: "personal-upfront-fee-override",
  monthlyFeeOverride: "personal-monthly-fee-override",
  riskWeightOverridePct: "capital-risk-override",
  taxRateOverridePct: "capital-tax-rate-override",
  capitalOverrideReason: "capital-override-reason",
  notes: "pl-notes",
};
